# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

builds:
  - id: darwin
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

  - id: windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: darwin
    ids:
      - darwin
    formats: ['tar.gz']
    files:
      - LICENSE.txt
      - README.md
      - dev.nils-silbernagel.fs-clip.plist

  - id: windows
    ids:
      - windows
    formats: ['zip']
    files:
      - LICENSE.txt
      - README.md

release:
  make_latest: false
  extra_files:
    - glob: ./scripts/install.sh
