# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

builds:
  - id: linux
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: linux
    formats: [ 'tar.gz' ]
    files:
      - LICENSE.txt
      - README.md
      - dev.nils-silbernagel.fs-clip.service

    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{ .Arch }}

release:
  make_latest: false

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums_linux.txt'
