name: Release

on:
  push:

permissions:
  contents: write
  packages: write

jobs:
  release-linux:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        id: owner
        env:
          REPO_OWNER: ${{ github.repository_owner }}
        run: |
          # strip to lowercase and expose as an output
          echo "lower_owner=${REPO_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: build/
          file: build/goreleaser-cross-x11.Dockerfile
          tags: goreleaser-cross-x11:latest
          load: true
          push: true
          cache-from: type=registry,ref=ghcr.io/${{ steps.owner.outputs.lower_owner }}/goreleaser-cross-x11:latest
          cache-to: type=registry,ref=ghcr.io/${{ steps.owner.outputs.lower_owner }}/goreleaser-cross-x11:latest,mode=max

      - name: Run GoReleaser
        run: |
          docker run --rm \
            -e GITHUB_TOKEN=${GITHUB_TOKEN} \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "${PWD}:/go/src/fs-clip" \
            -w /go/src/fs-clip \
            goreleaser-cross-x11 \
            release --snapshot --clean --config=.goreleaser.linux.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-mac-windows:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --snapshot --clean --config=.goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
