name: Relese

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release-linux:
    runs-on: ubuntu-24.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      -
        name: Build docker image
        run: docker build --tag 'goreleaser-cross-x11' --file build/go-releaser-x11.Dockerfile build/

      -
        name: Run GoReleaser
        run: |
          docker run --rm \
            -e GITHUB_TOKEN=${GITHUB_TOKEN}
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "${PWD}:/go/src/fs-clip" \
            -w /go/src/fs-clip \
            goreleaser-cross-x11 \
            release --clean --config=.goreleaser.linux.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-mac-windows:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean --config=.goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
